apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/todolist_db"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  CORS_ALLOWED_ORIGINS: "http://frontend-service"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
