apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todolist-prod

resources:
  - ../../base

patches:
  - path: patches/backend-config.yaml
  - path: patches/hpa.yaml

replicas:
  - name: backend
    count: 3
  - name: frontend
    count: 3

commonLabels:
  environment: production
