apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todolist-dev
type: Opaque
data:
  # base64 encoded: postgres
  username: cG9zdGdyZXM=
  # base64 encoded: secretpassword
  password: c2VjcmV0cGFzc3dvcmQ=
