apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todolist-staging

resources:
  - ../../base

patches:
  - path: patches/backend-config.yaml

replicas:
  - name: backend
    count: 2
  - name: frontend
    count: 2

commonLabels:
  environment: staging
